version: '3.1'

services:
  client_app:
    build:
      context: ClientApp
      dockerfile: Dockerfile.dev
    ports:
      - 5173:8000
    env_file:
      - ./ClientApp/.env.development.local

  server_app:
    build:
      ServerApp/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 1488:8080
      
