version: '3.1'

services:
  winter_frontend:
    build:
      context: ClientApp
      dockerfile: Dockerfile.dev
    container_name: winter_frontend
    restart: always
    volumes:
      - ./ClientApp:/app
    ports:
      - 5173:5173
    env_file:
      - ./ClientApp/.env.development.local

  winter_backend:
    build:
      ServerApp/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 1488:8080
      
